dataset:
    root: "./data"

    train:
        #viped         : "ViPeD.train"
        mot17         : "MOT17Det.train"
        #mot20         : "MOT20Det.train"
        #COCOPersons   : "COCOPersons.train"

    val:
        mot17: "MOT17Det.train"
        #mot20         : "MOT20Det.train"

    test:
        mot17         : "MOT17Det.test"
        #mot20         : "MOT20Det.test"


model:
    device               : "cuda"    # cpu or cuda
    backbone             : "resnet50"    # resnet50 or resnet101
    backbone_pretrained  : true   # on ImageNet
    coco_model_pretrained: true   # on COCO; if true, no need to load the pretrained backbone
    cache_folder         : "./model_zoo"
    max_dets_per_image   : 350
    nms                  : 0.5
    det_thresh           : 0.05
    freeze_backbone      : false


training:
    batch_size          : 4
    num_workers         : 4
    epochs              : 50
    checkpoint          : ""      # checkpoint to resume, useful for starting from an interrupted training
    pretrained_model    : ""      # pre-trained model to resume
    tensorboard_filename: "ViPeD_experiment"
    lr                  : 0.005
    momentum            : 0.9
    weight_decay        : 0.0005
    lr_gamma            : 0.1
    mixed_batch         : false
    tgt_images_in_batch : 0
    print_freq          : 100
    save_freq           : 1000
    log_loss            : 20
    percentage_val      : 100    # 1 - 100


test:
    phase             : "test"      # can be test or val
    pretrained_models :
        coco_resnet_50     : 'https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth'
        coco_resnet_101    : 'https://ababino-models.s3.amazonaws.com/resnet101_7a82fa4a.pth'
        mot17det_resnet_101: 'http://datino.isti.cnr.it/viped_model_zoo/coco_mot17det_resnet_101.zip'
        mot17det_resnet_50 : 'http://datino.isti.cnr.it/viped_model_zoo/coco_mot17det_resnet_50.zip'
    thresh            : 0.05
    percentage        : null
    evaluation_api    : "coco"   # can be mot or coco
    batch_size        : 8
    num_workers       : 8
    results_folder    : "./test_results"
